// Services registry — six capabilities, one team. Powers both the
// services.html overview grid and the service.html detail pages
// (service.js renders from this the same way project.js renders
// project.html from projects-data.js).
//
// `_ka` fields are picked by service.js when the page is under /ka/ —
// same convention as projects-data.js. Georgian copy is not filled in yet
// (English falls back everywhere a _ka field is missing).

export const services = [
  {
    slug: "strategy",
    index: "01",
    title: "Strategy & Creative Management",
    title_ka: "",
    eyebrow: "Service 01",
    heroTagline: "The engine underneath everything else — right before anything gets made.",
    heroTagline_ka: "",
    problem: "Good creative built on the wrong brief is just expensive guessing.",
    problem_ka: "",
    whatWeDo:
      "Before a single asset gets made, this is where the audience gets named, the brief gets right, and someone owns the outcome. Account management, brand positioning, and campaign management — one thread from pitch to delivery, not three separate handoffs.",
    whatWeDo_ka: "",
    chips: ["Account Management", "Brand Positioning", "Campaign Management"],
    chips_ka: null,
    price: "In Every Package",
    price_ka: "",
    process: [
      { title: "Discover", body: "Audience, competitors, and the actual business problem — named, not assumed." },
      { title: "Define", body: "A written strategy: positioning, voice, and what success looks like." },
      { title: "Direct", body: "The brief goes to the right discipline, with a strategist keeping it on course." },
      { title: "Deliver", body: "One owner accountable for the handoff — nothing lands without a check." },
    ],
    process_ka: null,
    deliverables: [
      "A written brand strategy document",
      "Positioning statement & audience profile",
      "A single accountable account owner",
      "A campaign timeline with real milestones",
    ],
    deliverables_ka: null,
    workFilter: null,
  },
  {
    slug: "brand",
    index: "02",
    title: "Brand & Graphic Design",
    title_ka: "",
    eyebrow: "Service 02",
    heroTagline: "The visual foundation everything else stands on.",
    heroTagline_ka: "",
    problem: "A brand that looks improvised gets treated like one.",
    problem_ka: "",
    whatWeDo:
      "A system, not a logo in isolation — type, color, and usage rules written down once so every future asset inherits it instead of reinventing it. Logos and full brand books, posters, banners, business cards, decks: one visual language across all of it.",
    whatWeDo_ka: "",
    chips: ["Visual Identity", "Brand Books", "Art Direction", "Collateral"],
    chips_ka: null,
    price: "Brand Book 1500–2500₾",
    price_ka: "",
    process: [
      { title: "Reference", body: "Pull from the brand strategy — voice and positioning come before pixels." },
      { title: "Explore", body: "Type, color, and mark direction — a few real options, not twenty half-ideas." },
      { title: "Systemize", body: "Rules get written down: spacing, pairing, what never happens to the mark." },
      { title: "Apply", body: "The system gets stress-tested across a deck, a post, and a package." },
    ],
    process_ka: null,
    deliverables: [
      "A complete brand guideline document",
      "Primary & secondary logo files",
      "A defined type & color system",
      "Ready-to-use collateral templates",
    ],
    deliverables_ka: null,
    workFilter: "Design",
  },
  {
    slug: "photo-video",
    index: "03",
    title: "Photo & Video Production",
    title_ka: "",
    eyebrow: "Service 03",
    heroTagline: "In-house studios. Rapid, high-quality content, no outside vendor tax.",
    heroTagline_ka: "",
    problem: "Phone photos flatten good products, and you've got three seconds before the thumb moves on.",
    problem_ka: "",
    whatWeDo:
      "Product and campaign shoots, short-form video, and brand films — shot, edited, retouched, and color-corrected by the same hands. Outsourced production means a new brief every time; in-house means the same eye and the same standard on every shoot.",
    whatWeDo_ka: "",
    chips: ["Product Shoots", "Brand Films", "Retouching", "Color Grade"],
    chips_ka: null,
    price: "From 200₾",
    price_ka: "",
    process: [
      { title: "Concept", body: "A short treatment — what the shot needs to prove, not just look like." },
      { title: "Shoot", body: "In-house studio and crew — no scheduling around an outside vendor." },
      { title: "Edit", body: "Color, motion, and sound handled by the same team that shot it." },
      { title: "Deliver", body: "Cut for the platform it's actually going to run on." },
    ],
    process_ka: null,
    deliverables: [
      "Finished, graded photo & video assets",
      "Platform-cut versions (feed, story, ad)",
      "Raw select files on request",
      "A repeatable shoot cadence",
    ],
    deliverables_ka: null,
    workFilter: "Photo",
  },
  {
    slug: "web",
    index: "04",
    title: "Web Development & Digital Platforms",
    title_ka: "",
    eyebrow: "Service 04",
    heroTagline: "Where the brand actually lives and operates.",
    heroTagline_ka: "",
    problem: "Your site is the one channel you own. Most look rented.",
    problem_ka: "",
    whatWeDo:
      "Sites, e-commerce platforms, and interactive builds designed and built in house — plus the internal tools most agencies never mention: client portals, admin panels, operational dashboards. Built to be used daily, not just launched once.",
    whatWeDo_ka: "",
    chips: ["Design & Build", "Internal Tools", "UI/UX", "Maintenance"],
    chips_ka: null,
    price: "2000–3000₾",
    price_ka: "",
    process: [
      { title: "Wireframe", body: "What has to happen on the page, before anything is styled." },
      { title: "Build", body: "Real code, real content — no placeholder text left behind." },
      { title: "Test", body: "Checked on the devices people actually use, not just a wide monitor." },
      { title: "Launch", body: "Shipped with a way to update it without calling us first." },
    ],
    process_ka: null,
    deliverables: [
      "A live, working site or platform",
      "Editable content — no developer required",
      "Documentation for anything custom-built",
      "A direct line for support after launch",
    ],
    deliverables_ka: null,
    workFilter: "Web",
  },
  {
    slug: "ai",
    index: "05",
    title: "Emerging Tech & AI Integration",
    title_ka: "",
    eyebrow: "Service 05",
    heroTagline: "Not a slide in a pitch deck — already running internally.",
    heroTagline_ka: "",
    problem: "Most \"AI-powered\" claims are marketing, not infrastructure.",
    problem_ka: "",
    whatWeDo:
      "Custom AI tooling for internal workflows or client-facing interactions, plus rapid generative prototyping for campaigns and moodboards before committing production time. The agency's own client intake and internal team assistant already run on this — before it's ever offered to a client, and always reviewed by a person before anything ships.",
    whatWeDo_ka: "",
    chips: ["AI Workflows", "Generative Prototyping", "Reviewed By A Person"],
    chips_ka: null,
    price: "Custom Quote",
    price_ka: "",
    process: [
      { title: "Identify", body: "Find the repetitive step actually worth automating — not everything is." },
      { title: "Prototype", body: "A working version, tested internally before it touches client work." },
      { title: "Review", body: "A person checks the output — AI drafts, it doesn't decide." },
      { title: "Integrate", body: "Folded into the existing workflow, not a separate tool to remember." },
    ],
    process_ka: null,
    deliverables: [
      "A working, reviewed AI workflow",
      "Faster first-draft turnaround",
      "Documentation of what's automated",
      "No black-box decisions on your brand",
    ],
    deliverables_ka: null,
    workFilter: null,
  },
  {
    slug: "marketing",
    index: "06",
    title: "Digital Marketing & Distribution",
    title_ka: "",
    eyebrow: "Service 06",
    heroTagline: "The best work in the world does nothing sitting unseen.",
    heroTagline_ka: "",
    problem: "Posting when you remember to isn't a strategy, and good content nobody sees is a diary, not marketing.",
    problem_ka: "",
    whatWeDo:
      "Full page management with a content plan that actually ships, paid campaigns across Meta, Google, and LinkedIn, and copy that sounds like the brand instead of a template — targeted, measured, and reported in numbers you can check yourself.",
    whatWeDo_ka: "",
    chips: ["Social Management", "Paid Social", "SEO", "Copywriting"],
    chips_ka: null,
    price: "In Packages — See Pricing",
    price_ka: "",
    process: [
      { title: "Plan", body: "A calendar sized to the tier — rhythm, not a random content dump." },
      { title: "Publish", body: "Platform-native formatting — a Reel isn't a resized ad." },
      { title: "Optimize", body: "Paid spend adjusted toward what's actually converting." },
      { title: "Report", body: "Real numbers, reviewed together — not a vanity-metrics deck." },
    ],
    process_ka: null,
    deliverables: [
      "A live content calendar",
      "Managed paid ad campaigns",
      "On-voice copy across channels",
      "Regular performance reporting",
    ],
    deliverables_ka: null,
    workFilter: null,
  },
];

export function getService(slug) {
  return services.find((s) => s.slug === slug);
}
